package com.example.tankcontrol

enum class Lang { EN, FA }

/**
 * All user-facing text, in both supported languages. The app switches
 * between these at runtime (independent of the phone's system locale),
 * based on the language chosen on first run / in Settings.
 */
data class AppStrings(
    val aboutCredit: String,
    val chooseLanguageTitle: String,
    val english: String,
    val farsi: String,
    val continueLabel: String,

    val setupTitle: String,
    val setupPrompt: String,
    val enter: String,
    val save: String,
    val phoneHint: String,

    val tanksPrompt: String,
    val tanksLabel: String,

    val gsm: String,
    val nrf: String,
    val antCheckDesc: String,

    val home: String,
    val settings: String,
    val tankTab: String,

    val settingsTitle: String,
    val settingsAccount: String,
    val settingsLanguage: String,
    val settingsSim: String,
    val settingsHelp: String,
    val settingsTankCount: String,
    val settingsAbout: String,
    val settingsAutoUpdate: String,
    val autoOff: String,
    val autoOnOpen: String,
    val back: String,

    val accountTitle: String,
    val contactName: String,
    val contactNumber: String,

    val simTitle: String,
    val simPrompt: String,

    val helpTitle: String,
    val helpIntro: String,
    val helpStep1Title: String,
    val helpStep1Body: String,
    val helpStep2Title: String,
    val helpStep2Body: String,
    val helpStep3Title: String,
    val helpStep3Body: String,
    val helpStep4Title: String,
    val helpStep4Body: String,
    val helpStep5Title: String,
    val helpStep5Body: String,

    val tankHeightPrompt: String,
    val pumpOnPrompt: String,
    val pumpOffPrompt: String,
    val diameterPrompt: String,
    val diameterSave: String,
    val checkNow: String,
    val liters: String,
    val cm: String,
    val notSetYet: String,
    val noReply: String,
    val tankCountRangeError: String,
    val offMustExceedOnError: String,

    val updateTankStatus: String,
    val updateAntennaStatus: String,
    val allSavedMessage: String,
    val chooseSimTitle: String,
    val lastUpdated: String,
    val defaultsReminder: String,
    val registeringDefaults: String,
    val smsPermissionWarning: String,

    val settingsReliability: String,
    val reliabilityTitle: String,
    val reliabilityIntro: String,
    val reliabilityBatteryButton: String,
    val reliabilityBatteryDone: String,
    val reliabilityAutostartButton: String,
    val reliabilityAutostartDesc: String,
    val reliabilityNotificationButton: String,
    val reliabilityNotificationDone: String,
    val reliabilityNotificationDesc: String
)

val EnStrings = AppStrings(
    aboutCredit = "Built by Mohammad Amin Norouzi",
    chooseLanguageTitle = "Choose your language",
    english = "English",
    farsi = "Persian (فارسی)",
    continueLabel = "Continue",

    setupTitle = "Liquid level controler",
    setupPrompt = "Please enter the SIM card phone number installed on the mother board",
    enter = "ENTER",
    save = "SAVE",
    phoneHint = "+98**********",

    tanksPrompt = "Please enter the desired number of tanks (maximum 4 tanks can be connected)",
    tanksLabel = "Tanks:",

    gsm = "GSM",
    nrf = "NRF",
    antCheckDesc = "Refresh signal status",

    home = "Home",
    settings = "Settings",
    tankTab = "Tank",

    settingsTitle = "Settings",
    settingsAccount = "Account",
    settingsLanguage = "Language",
    settingsSim = "SIM card",
    settingsHelp = "Guide",
    settingsTankCount = "Change tank count",
    settingsAbout = "About us",
    settingsAutoUpdate = "Automatic status update",
    autoOff = "Off",
    autoOnOpen = "When the app opens",
    back = "Back",

    accountTitle = "Account",
    contactName = "Your name",
    contactNumber = "Your phone number",

    simTitle = "Mother board SIM number",
    simPrompt = "The app sends all commands to this number",

    helpTitle = "Guide",
    helpIntro = "A quick walkthrough of every part of the app.",
    helpStep1Title = "1. First launch",
    helpStep1Body = "Pick English or Persian, then enter the phone number of the SIM card installed on the mother board -- every command goes to that number. On a dual-SIM phone you can also pick which of your SIM cards the app sends from.",
    helpStep2Title = "2. Setting up tanks",
    helpStep2Body = "Enter how many tanks are connected (1-4). The app then walks you through each one: height, then the pump's ON% and OFF%. It automatically checks each tank before moving to the next, and refreshes the antenna status once every tank is done. Change the count again anytime from Settings.",
    helpStep3Title = "3. Home screen",
    helpStep3Body = "The top panel shows GSM signal and every tank's NRF signal as a score and four bars -- tap the refresh icon inside it to update. Below that, each tank has its own glass-style card showing percent, liters, whether the pump is ON or OFF, and when it was last updated. The app also re-checks every tank automatically each time you open it. When restoring saved defaults, the screen is dimmed and locked until all tank CHECK replies are received; the antenna check is sent afterward and the screen becomes normal before that final antenna check finishes.",
    helpStep4Title = "4. Each tank's page",
    helpStep4Body = "Open Tank1, Tank2, etc. from the bottom bar. Tap the height arrow, either pump arrow, or the diameter arrow above the tank to edit that value -- tapping anywhere else cancels the edit. The circular icon near the bottom re-checks that one tank on demand.",
    helpStep5Title = "5. Settings",
    helpStep5Body = "Account: your name and, on dual-SIM phones, which SIM to send from. Language, SIM card, and Change tank count do what they say. About us shows who built the app.",

    tankHeightPrompt = "Please enter the tank height (cm)",
    pumpOnPrompt = "Please enter water percentage to activate the pump",
    pumpOffPrompt = "Please enter water percentage to deactivate the pump",
    diameterPrompt = "Tank diameter (cm), for liters",
    diameterSave = "SAVE",
    checkNow = "Check",
    liters = "L",
    cm = "cm",
    notSetYet = "Not checked yet",
    noReply = "No reply received. Please try again.",
    tankCountRangeError = "Tank count must be between 1 and 4",
    offMustExceedOnError = "OFF must be greater than ON, and 100 or lower",

    updateTankStatus = "Update tank status",
    updateAntennaStatus = "Update antenna status",
    allSavedMessage = "All defaults saved",
    chooseSimTitle = "Send from which SIM on this phone?",
    lastUpdated = "Last updated",
    defaultsReminder = "Please re-enter the defaults",
    registeringDefaults = "Registering...",
    smsPermissionWarning = "SMS receive permission is off -- replies from the board can't arrive. Please enable it in phone settings.",

    settingsReliability = "SMS reliability",
    reliabilityTitle = "SMS reliability",
    reliabilityIntro = "Some phone brands aggressively shut down apps running in the background, which can stop the board's SMS replies from getting through. These two steps make that much less likely.",
    reliabilityBatteryButton = "Exempt this app from battery optimization",
    reliabilityBatteryDone = "Already exempted on this phone",
    reliabilityAutostartButton = "Open autostart / background permission settings",
    reliabilityAutostartDesc = "On Xiaomi, Huawei, Oppo, Vivo, Samsung, OnePlus and similar phones, also allow this app to \"autostart\" or run in the background from that vendor's own settings screen.",
    reliabilityNotificationButton = "Grant SMS notification access",
    reliabilityNotificationDone = "Notification access already granted",
    reliabilityNotificationDesc = "Also grant notification access -- if a reply's SMS broadcast is ever missed, the app can still pick it up from the phone's messaging-app notification instead."
)

val FaStrings = AppStrings(
    aboutCredit = "ساخته شده توسط محمد امین نوروزی",
    chooseLanguageTitle = "زبان خود را انتخاب کنید",
    english = "انگلیسی",
    farsi = "فارسی",
    continueLabel = "ادامه",

    setupTitle = "Liquid level controler",
    setupPrompt = "لطفاً شماره سیم‌کارت نصب‌شده روی مادربرد را وارد کنید",
    enter = "ثبت",
    save = "ذخیره",
    phoneHint = "+98**********",

    tanksPrompt = "لطفاً تعداد تانکر مورد نظر را وارد کنید (حداکثر ۴ تانکر قابل اتصال است)",
    tanksLabel = "تعداد تانکر:",

    gsm = "GSM",
    nrf = "NRF",
    antCheckDesc = "به‌روزرسانی وضعیت آنتن",

    home = "خانه",
    settings = "تنظیمات",
    tankTab = "تانکر",

    settingsTitle = "تنظیمات",
    settingsAccount = "حساب کاربری",
    settingsLanguage = "زبان",
    settingsSim = "سیم‌کارت",
    settingsHelp = "راهنما",
    settingsTankCount = "تغییر تعداد تانکر",
    settingsAbout = "درباره ما",
    settingsAutoUpdate = "بروز کردن وضعیت خودکار",
    autoOff = "خاموش",
    autoOnOpen = "زمانی که برنامه باز شود",
    back = "بازگشت",

    accountTitle = "حساب کاربری",
    contactName = "نام شما",
    contactNumber = "شماره تلفن شما",

    simTitle = "شماره سیم‌کارت مادربرد",
    simPrompt = "نرم‌افزار تمام دستورات را به این شماره پیامک می‌کند",

    helpTitle = "راهنما",
    helpIntro = "توضیح کوتاه هر بخش از نرم‌افزار.",
    helpStep1Title = "۱. اولین اجرا",
    helpStep1Body = "زبان انگلیسی یا فارسی را انتخاب کنید، سپس شماره سیم‌کارت نصب‌شده روی مادربرد را وارد کنید -- تمام دستورات به همین شماره ارسال می‌شود. روی گوشی‌های دو سیم‌کارت، می‌توانید انتخاب کنید نرم‌افزار از کدام سیم‌کارت پیامک بفرستد.",
    helpStep2Title = "۲. تنظیم تانکرها",
    helpStep2Body = "تعداد تانکرهای متصل (۱ تا ۴) را وارد کنید. نرم‌افزار شما را قدم‌به‌قدم راهنمایی می‌کند: ابتدا ارتفاع، سپس درصد روشن‌شدن و خاموش‌شدن پمپ برای هر تانکر. قبل از رفتن به تانکر بعدی، خودش وضعیت همان تانکر را چک می‌کند و بعد از تمام‌شدن همه، وضعیت آنتن را هم به‌روز می‌کند. تعداد تانکر را بعداً هم از تنظیمات می‌توانید عوض کنید.",
    helpStep3Title = "۳. صفحه خانه",
    helpStep3Body = "کادر بالا، کیفیت آنتن جی‌اس‌ام و آنتن هر تانکر را به‌صورت عدد و چهار خط نشان می‌دهد -- برای به‌روزرسانی، روی آیکون رفرش داخل همان کادر بزنید. پایین‌تر، هر تانکر یک کارت شیشه‌ای دارد که درصد، لیتر، روشن یا خاموش بودن پمپ، و ساعت آخرین به‌روزرسانی را نشان می‌دهد. هر بار که نرم‌افزار را باز کنید، خودش هم تمام تانکرها را دوباره چک می‌کند. هنگام بازیابی دیفالت‌ها، صفحه تار و قفل می‌شود تا پاسخ CHECK همه تانکرها دریافت شود؛ بعد از آن چک آنتن ارسال می‌شود و صفحه قبل از پایان چک آنتن دوباره عادی می‌شود.",
    helpStep4Title = "۴. صفحه هر تانکر",
    helpStep4Body = "از نوار پایین صفحه، Tank1، Tank2 و... را باز کنید. روی فلش ارتفاع، هر کدام از فلش‌های پمپ، یا فلش قطر بالای تانکر بزنید تا آن مقدار را ویرایش کنید -- زدن هر جای دیگه آن ویرایش را لغو می‌کند. آیکون دایره‌ای پایین صفحه، همان یک تانکر را دوباره چک می‌کند.",
    helpStep5Title = "۵. تنظیمات",
    helpStep5Body = "حساب کاربری: نام شما و، روی گوشی‌های دو سیم‌کارت، سیم‌کارت ارسال‌کننده. زبان، سیم‌کارت، و تغییر تعداد تانکر همان کاری را می‌کنند که از اسمشان پیداست. درباره ما هم سازنده برنامه را نشان می‌دهد.",

    tankHeightPrompt = "لطفاً ارتفاع مخزن را وارد کنید (سانتی‌متر)",
    pumpOnPrompt = "لطفاً درصد آب برای فعال‌سازی پمپ را وارد کنید",
    pumpOffPrompt = "لطفاً درصد آب برای غیرفعال‌سازی پمپ را وارد کنید",
    diameterPrompt = "قطر تانکر (سانتی‌متر)، برای محاسبه لیتر",
    diameterSave = "ذخیره",
    checkNow = "بررسی",
    liters = "لیتر",
    cm = "سانتی‌متر",
    notSetYet = "هنوز بررسی نشده",
    noReply = "پاسخی دریافت نشد. دوباره تلاش کنید.",
    tankCountRangeError = "تعداد تانکر باید بین ۱ تا ۴ باشد",
    offMustExceedOnError = "درصد خاموش‌شدن باید بیشتر از درصد روشن‌شدن، و حداکثر ۱۰۰ باشد",

    updateTankStatus = "بروز کردن وضعیت تانکر",
    updateAntennaStatus = "بروز کردن وضعیت آنتن",
    allSavedMessage = "تمام دیفالت‌ها ذخیره شدند",
    chooseSimTitle = "پیامک با کدام سیم‌کارت این گوشی ارسال شود؟",
    lastUpdated = "آخرین به‌روزرسانی",
    defaultsReminder = "لطفاً دیفالت‌ها را مجدداً وارد کنید",
    registeringDefaults = "در حال ثبت شدن",
    smsPermissionWarning = "لطفاً مجوز دریافت پیامک رو در تنظیمات گوشی فعال کنید",

    settingsReliability = "پایداری دریافت پیامک",
    reliabilityTitle = "پایداری دریافت پیامک",
    reliabilityIntro = "بعضی برندهای گوشی به‌صورت خیلی سخت‌گیرانه اپ‌های در حال اجرا در پس‌زمینه رو می‌بندن، که می‌تونه باعث بشه ریپلای پیامکی مادربرد به دست نرم‌افزار نرسه. این دو مرحله این احتمال رو خیلی کم می‌کنه.",
    reliabilityBatteryButton = "معاف کردن این اپ از بهینه‌سازی باتری",
    reliabilityBatteryDone = "روی این گوشی از قبل معاف شده",
    reliabilityAutostartButton = "باز کردن تنظیمات اجرای خودکار / پس‌زمینه",
    reliabilityAutostartDesc = "روی گوشی‌های شیائومی، هواوی، اوپو، ویوو، سامسونگ، وان‌پلاس و مشابه، از تنظیمات اختصاصی همون گوشی هم اجازه‌ی «اجرای خودکار» یا اجرا در پس‌زمینه رو به این اپ بدید.",
    reliabilityNotificationButton = "دادن دسترسی نوتیفیکیشن پیامک",
    reliabilityNotificationDone = "دسترسی نوتیفیکیشن از قبل داده شده",
    reliabilityNotificationDesc = "دسترسی نوتیفیکیشن رو هم بدید -- اگه یه بار پیامک ریپلای از مسیر اصلی گم بشه، نرم‌افزار می‌تونه همون پیام رو از نوتیفیکیشن اپ پیامک هم بخونه."
)

fun stringsFor(lang: Lang): AppStrings = if (lang == Lang.FA) FaStrings else EnStrings
